import time
from selenium import webdriver
driver = webdriver.Chrome()
driver.get("http://localhost:8081/HKR")
driver.maximize_window()
time.sleep(3)
driver.find_element_by_xpath("/html/body/div/div/div[1]/div[2]/a[2]").click()
time.sleep(3)
driver.find_element_by_xpath("//*[@id='loginname']").send_keys("tonghe")
time.sleep(3)
driver.find_element_by_xpath("//*[@id='password']").send_keys("root")
time.sleep(3)
driver.find_element_by_xpath("//*[@id='submit']").click()
time.sleep(3)
driver.find_element_by_xpath("/html/body/div[3]/div[2]/div/li[1]/ul/li[1]/div/span[4]/a").click()
time.sleep(3)
driver.find_element_by_xpath("//*[@id='sear_teaname']").send_keys("贾")
time.sleep(3)
driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div/div/div[1]/table/tbody/tr/td[2]/a/span/span[1]").click()
time.sleep(3)
driver.find_element_by_xpath("/html/body/div[4]/div[2]/div[2]/div[2]/div/div[1]/div[2]/div/div/div[2]/div[2]/div[2]/table/tbody/tr/td[9]/div/a").click()
time.sleep(3)
driver.quit()
